[package]
name = "fso-graph-builder"
version = "0.4.3"
description = "A building block for high-performant graph algorithms. Community-maintained fork of graph_builder."
keywords = ["graph", "builder", "csr", "algorithms"]
categories = ["data-structures", "algorithms", "parser-implementations", "concurrency"]
homepage = "https://github.com/fluminis-scientiae-oraculum/fso-graph"
documentation = "https://docs.rs/fso-graph-builder"
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "fso_graph_builder"

[dependencies]
atoi.workspace = true
atomic.workspace = true
byte-slice-cast.workspace = true
bytemuck.workspace = true
dashmap.workspace = true
delegate.workspace = true
fast-float2.workspace = true
rustc-hash.workspace = true
gdl = { workspace = true, optional = true }
linereader.workspace = true
log.workspace = true
memmap2.workspace = true
num.workspace = true
num-format.workspace = true
num_cpus.workspace = true
page_size.workspace = true
parking_lot.workspace = true
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-compression.workspace = true
criterion.workspace = true
directories.workspace = true
futures.workspace = true
rand.workspace = true
reqwest.workspace = true
tap.workspace = true
tempfile.workspace = true
astral-tokio-tar.workspace = true
tokio-util.workspace = true
tokio.workspace = true

[features]
force_fallback_impl = []
dotgraph = []

[lints]
workspace = true

[[bench]]
name = "edgelist"
harness = false

[[bench]]
name = "topology"
harness = false

[[bench]]
name = "dotgraph"
harness = false

[package.metadata.docs.rs]
features = ["gdl", "dotgraph"]
