[workspace]

members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = [
    "Martin Junghanns <github@s1ck.dev>",
    "Paul Horn <developer@knutwalker.de>",
]
rust-version = "1.82"
repository = "https://github.com/neo4j-labs/graph"
edition = "2021"
license = "MIT"

[workspace.dependencies]
ahash = "0.8.12"
arrow = "58"
arrow-flight = "58"
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
astral-tokio-tar = "0.6.2"
async-trait = "0.1.89"
atoi = "2.0.0"
atomic = "0.6"
atomic_float = "1.1"
byte-slice-cast = "1.2"
bytemuck = "1"
clap = { version = "4.6", features = ["derive"] }
criterion = { version = "0.8", features = ["html_reports"] }
dashmap = "6.2"
delegate = "0.13"
directories = "6"
env_logger = "0.11"
fast-float2 = "0.2.3"
float-ord = "0.3.2"
futures = "0.3"
fxhash = "0.2.1"
gdl = "0.2.7"
itertools = "0.14"
linereader = "0.4.0"
log = "0.4"
memmap2 = "0.9"
nanorand = "0.7.0"
num = "0.4"
num_cpus = "1.16"
num-format = "0.4"
numpy = "0.28"
page_size = "0.6"
parking_lot = "0.12"
pico-args = "0.5"
polars = { version = "0.53", default-features = false, features = ["fmt"] }
pyo3 = "0.28"
pyo3-log = "0.13"
rand = "0.10"
rayon = "1.12"
reqwest = { version = "0.13", features = ["stream"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tap = "1"
tempfile = "3.27"
thiserror = "2"
tokio = { version = "1", features = ["full"], default-features = true }
tokio-util = { version = "0.7", features = ["io"] }
tonic = "0.14"

[workspace.metadata.release]
pre-release-commit-message = "Release {{crate_name}} {{version}}"
